// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpbcaynwwjuizdmcudnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYmNheW53d2p1aXpkbWN1ZG5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDI3ODYsImV4cCI6MjA3MjM3ODc4Nn0.h3vc52VMdp87lUGHolsPSPmdkeV-akYzq9GpmOIh0Y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});